name: 04 - Using Actions
on: push 

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      # Step 1: Checkout the repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2:L Print out the file structure
      - name: List files
        run: ls -R
