name: 04 - Using Actions
on: push 

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      # Step 1: Checkout the repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      
      # Step 3: Install 
      - name: Install Dependencies
        run: npm ci

